spring:
  datasource:
    url: jdbc:h2:file:./data/dataprover;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

dataprover:
  storage:
    rocksdb-path: ./data/rocksdb
    cache-size-mb: 128

logging:
  level:
    com.bloxbean.cardano: DEBUG
